// generated by authenticaTed v1.0.0 at 2016-12-27 20:21:22.129387322 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:21:13.322754958 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:38.591073429 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:25.441496907 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:19.733390956 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:14.463489356 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:13.098188549 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:04.76524313 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:19:04.451104719 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:18:58.9036983 -0300 BRT

package util

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestGeneratePrime(t *testing.T) {
	types := []int{32, 64}

	for _, tt := range types {
		i, err := GeneratePrime(tt)
		assert.NoError(t, err)
		assert.NotZero(t, i)
	}
}
