// generated by authenticaTed v1.0.0 at 2016-12-27 20:21:22.129595662 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:21:13.322986753 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:38.591272668 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:25.441683239 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:19.733589368 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:14.463674671 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:13.098479937 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:04.765439419 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:19:04.45128643 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:18:58.904046645 -0300 BRT

package util

import (
	"strconv"

	"github.com/c2h5oh/hide"
)

// HideToString converts hide.Int64 into string
func HideToString(id hide.Int64) string {
	return strconv.FormatInt(int64(id), 10)
}

// HideToByte converts hide.Int64 into byte slice
func HideToByte(id hide.Int64) []byte {
	return []byte(HideToString(id))
}

func Obfuscate(id hide.Int64) int64 {
	return hide.Int64Obfuscate(int64(id), nil, nil)
}

func Deobfuscate(id int64) hide.Int64 {
	return hide.Int64(hide.Int64Deobfuscate(int64(id), nil, nil))
}
