swagger: "2.0"

info:
  version: "1.0.0"
  title: authenticaTed
  license:
    name: MIT
    url: "https://github.com/UnnoTed/authenticaTed/blob/master/LICENSE"

#basePath: "/api/v1"

definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      username:
        type: string
  Error:
    properties:
      success: 
        type: boolean
      error:
        type: object
        properties:
          code:
            type: integer
            format: int32
          message:
            type: string
          language:
            type: string

paths:
  /users:
    get:
      description: |
        List of registered users.
        
        Minimum power required: `auth.UserPowerAdmin`
      parameters:
        -
          name: limit
          in: query
          description: Limit of users
          required: false
          type: integer
          format: int64
        -
          name: offset
          in: query
          description: Where the array should start
          required: false
          type: integer
          format: int64
      responses:
        200:
          description: List of users
          schema:
            type: object
            properties:
              success:
                type: boolean
              users:
                title: Array of Users
                type: array
                items:
                  $ref: "#/definitions/User"
        500:
          description: Server Error
          schema:
            $ref: "#/definitions/Error"
    post:
      description: |
        Create a new user
      responses:
        200:
          description: List of users
          schema:
            type: object
            properties:
              success:
                type: boolean
              user:
                $ref: "#/definitions/User"
        default:
          description: Server Error
          schema:
            $ref: "#/definitions/Error"
  /users/{id}:
    get:
      description: hello
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to retrieve
          type: string
      responses:
        200:
          description: List of users
          schema:
            type: object
            properties:
              success:
                type: boolean
              users:
                title: Array of Users
                type: array
                items:
                  $ref: "#/definitions/User"
        default:
          description: Server Error
          schema:
            $ref: "#/definitions/Error"
              
              
