// generated by authenticaTed v1.0.0 at 2016-12-27 20:21:22.120668868 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:21:13.315059103 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:38.583117596 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:25.433868531 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:19.725842704 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:14.455906236 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:13.090746302 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:20:04.757650916 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:19:04.443325157 -0300 BRT

// generated by authenticaTed v1.0.0 at 2016-12-27 20:18:58.893454408 -0300 BRT

package logger

import log "github.com/Sirupsen/logrus"

var Logger = log.New()

func init() {
	// Log as JSON instead of the default ASCII formatter.
	//log.SetFormatter(&log.JSONFormatter{})

	// Output to stderr instead of stdout, could also be a file.
	//log.SetOutput(os.Stderr)

	// Only log the warning severity or above.

	Logger.Level = log.ErrorLevel

	Logger.Formatter = &log.TextFormatter{ForceColors: true}

	// use the line below to see the db log

}
